# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49b4deba0ffd4075f8ee0fa530b4f510189dfe6c6aa7c454155867740809358bedef94fa15afc50365834e3794577a90e261fe0c61dd0f2437b29583f1c913c0

test:
  secret_key_base: 5e6b89e03f3b48c27d0498255efef455ea0333f33da1927c626adc32c1dbebfb10cf42431874e7ae753e590b7a80796688b8bf0b70c994d45657e633d1cefa6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
